<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attendance Report - {{ $periodLabel }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; }
        h1, h2 { margin: 0; }
        .muted { color: #6b7280; }
        .header { border-bottom: 2px solid #0f766e; padding-bottom: 12px; margin-bottom: 18px; }
        .grid { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        .grid td { width: 20%; border: 1px solid #e5e7eb; padding: 10px; vertical-align: top; }
        .value { font-size: 20px; font-weight: bold; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #f3f4f6; text-align: left; }
        th, td { border: 1px solid #e5e7eb; padding: 6px; }
        .section { margin-top: 18px; }
        .bar { height: 8px; background: #e5e7eb; border-radius: 4px; overflow: hidden; }
        .bar span { display: block; height: 8px; background: #0f766e; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $settings->company_name }}</h1>
        <p class="muted">{{ $settings->company_address }}</p>
        <h2>Attendance Report - {{ $periodLabel }}</h2>
        <p class="muted">Generated by {{ $generatedBy->name }} on {{ now()->format('M d, Y H:i') }}</p>
    </div>

    <table class="grid">
        <tr>
            <td>
                <div class="muted">Present</div>
                <div class="value">{{ $statusCounts['present'] }}</div>
            </td>
            <td>
                <div class="muted">Late</div>
                <div class="value">{{ $statusCounts['late'] }}</div>
            </td>
            <td>
                <div class="muted">Absent</div>
                <div class="value">{{ $statusCounts['absent'] }}</div>
            </td>
            <td>
                <div class="muted">On Leave</div>
                <div class="value">{{ $statusCounts['on_leave'] }}</div>
            </td>
            <td>
                <div class="muted">Attendance Rate</div>
                <div class="value">{{ $attendancePercent }}%</div>
            </td>
        </tr>
    </table>

    <div class="section">
        <h2>Employee Summary</h2>
        <table>
            <thead>
                <tr>
                    <th>Employee</th>
                    <th>Department</th>
                    <th>Present</th>
                    <th>Late</th>
                    <th>Absent</th>
                    <th>On Leave</th>
                    <th>Rate</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($employeeSummary as $employee)
                    <tr>
                        <td>{{ $employee['name'] }}</td>
                        <td>{{ $employee['department'] }}</td>
                        <td>{{ $employee['present'] }}</td>
                        <td>{{ $employee['late'] }}</td>
                        <td>{{ $employee['absent'] }}</td>
                        <td>{{ $employee['on_leave'] }}</td>
                        <td>{{ $employee['attendance_percent'] }}%</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7">No attendance records found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Attendance Records</h2>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Employee</th>
                    <th>Department</th>
                    <th>Status</th>
                    <th>Check In</th>
                    <th>Check Out</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($records as $record)
                    <tr>
                        <td>{{ $record->attendance_date->format('M d, Y') }}</td>
                        <td>{{ $record->user?->name ?? '-' }}</td>
                        <td>{{ $record->user?->department?->name ?? 'No department' }}</td>
                        <td>{{ ucfirst(str_replace('_', ' ', $record->status)) }}</td>
                        <td>{{ $record->check_in_at?->format('H:i') ?? '-' }}</td>
                        <td>{{ $record->check_out_at?->format('H:i') ?? '-' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="6">No attendance records found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</body>
</html>
